### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by qbnil** [InioX/dotfiles-hyprland#3]
Hey, first of all, thx for these dots. Can you share that awesome wallpaper tho 1920x1080

**Comment by qbnil** [comment]
Figured it already, thx

**Comment by qbnil** [comment]
The only issue i got was: Config error at line 67(/home/archi/.config/hypr/hyprland.conf): Error setting value <on> for field <decoration:blur_new_optimization>: No such field

**Comment by InioX** [comment]
Hi,

I already fixed that error on NixOS branch but forgot on Arch, I'll push a fix as soon as I'm on my pc.

Thanks for the notice.

**Comment by qbnil** [comment]
Alr, appreciate the effort
