### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by FatngatirBilek** [InioX/dotfiles-hyprland#5]
i'm new with nixos.. after followed your instructions this happened

Please specify the name of the NixOS configuration to be installed, as a URI fragment in the flake-uri.
For example, to use the output nixosConfigurations.foo from the flake.nix, append "#foo" to the flake-uri.

**Comment by InioX** [comment]
Hi!

Do you mean this line inside `install.sh`?

https://github.com/InioX/dotfiles/blob/c2c480615c9b96ddde8331eb37e2d0f9b411db7d/install.sh#L3

**Comment by FatngatirBilek** [comment]
yep
