### ISSUE TITLE
Error setting value <1> for field <decoration:blur_passes> no such field

### ISSUE THREAD

**Issue by qbnil** [InioX/dotfiles-hyprland#6]
Hey, just a small issue ig, on line 66 hyprland.conf

**Comment by InioX** [comment]
Hi!

What branch is the error happening on?

**Comment by qbnil** [comment]
on the arch one

**Comment by qbnil** [comment]
did you manage to figure this out eventually?

**Comment by InioX** [comment]
I just removed it from my config and disabled blur completely

Here is the latest [config](https://github.com/InioX/dotfiles/blob/nixos/dotfiles/config/hypr/hyprland.conf)
